// NOTE: THIS IS NOT USED BY THE MAIN GAME!
// THIS SCRIPT IS ONLY USED BY THE MEGA SPRITESHEET PROCESS STEP, ImageStitch.html
var fileList = ["images\\check.png",
"images\\checkBox.png",
"images\\checkForCheckBox.png",
"images\\placeholderPlayButtonImage.png",
"images\\Backgrounds\\airBooth.png",
"images\\Backgrounds\\airBoothPlasticLayer.png",
"images\\Backgrounds\\airBoothTopLayer.png",
"images\\Backgrounds\\balloonBackground.png",
"images\\Backgrounds\\Barn.png",
"images\\Backgrounds\\bottomWall.png",
// "images\\Backgrounds\\bubbleWrapBG.jpg
"images\\Backgrounds\\car.png",
"images\\Backgrounds\\Cliff.png",
"images\\Backgrounds\\cloud1.png",
"images\\Backgrounds\\cloud2.png",
"images\\Backgrounds\\cloud3.png",
"images\\Backgrounds\\cloud4.png",
"images\\Backgrounds\\clouds.png",
"images\\Backgrounds\\daytimeBackground.png",
"images\\Backgrounds\\dodgeball.png",
"images\\Backgrounds\\editedJumperBackground.png",
"images\\Backgrounds\\feed.png",
"images\\Backgrounds\\FinderBG.png",
"images\\Backgrounds\\Flower.png",
"images\\Backgrounds\\Flower2.png",
"images\\Backgrounds\\flyingBee.png",
"images\\Backgrounds\\Grass.png",
"images\\Backgrounds\\Lake.png",
"images\\Backgrounds\\LaneGrass1.png",
"images\\Backgrounds\\LaneGrass2.png",
"images\\Backgrounds\\leftWall.png",
"images\\Backgrounds\\Lily.png",
"images\\Backgrounds\\mazefloor.png",
"images\\Backgrounds\\menu_border.png",
"images\\Backgrounds\\nighttimeBackground.png",
"images\\Backgrounds\\Penalty.png",
"images\\Backgrounds\\rightWall.png",
"images\\Backgrounds\\river.png",
"images\\Backgrounds\\road.png",
"images\\Backgrounds\\road1.png",
"images\\Backgrounds\\road2.png",
"images\\Backgrounds\\roadDash.png",
"images\\Backgrounds\\roadDash2.png",
"images\\Backgrounds\\roadDash3.png",
"images\\Backgrounds\\runnerCloud1.png",
"images\\Backgrounds\\runnerGrass.png",
"images\\Backgrounds\\runnerMountain1.png",
"images\\Backgrounds\\runnerSunAndSky.png",
"images\\Backgrounds\\scoreboard_overlay.png",
"images\\Backgrounds\\ShootGallery.png",
"images\\Backgrounds\\Sky.png",
"images\\Backgrounds\\Space.png",
"images\\Backgrounds\\Space2.png",
"images\\Backgrounds\\spaceBackgroundForVolcanoGame.png",
"images\\Backgrounds\\SpaceWithJupiter1.png",
"images\\Backgrounds\\SpaceWithJupiter2.png",
"images\\Backgrounds\\spellingBee.png",
"images\\Backgrounds\\target.png",
"images\\Backgrounds\\tiled1.png",
"images\\Backgrounds\\topWall.png",
"images\\Backgrounds\\underwater.png",
"images\\Backgrounds\\underwater2.png",
"images\\Backgrounds\\vacuumBackground.png",
"images\\Backgrounds\\Volcano.png",
"images\\Backgrounds\\Wack.png",
"images\\Backgrounds\\WackTableBeneathSurface.png",
"images\\Backgrounds\\WackTableSurface.png",
"images\\Backgrounds\\wave.png",
"images\\Backgrounds\\whackALetterTile.png",
"images\\Custom Font\\original pdns\\symbols\\symbol!.png",
"images\\Custom Font\\pngs\\big letters\\biga.png",
"images\\Custom Font\\pngs\\big letters\\bigb.png",
"images\\Custom Font\\pngs\\big letters\\bigc.png",
"images\\Custom Font\\pngs\\big letters\\bigd.png",
"images\\Custom Font\\pngs\\big letters\\bige.png",
"images\\Custom Font\\pngs\\big letters\\bigf.png",
"images\\Custom Font\\pngs\\big letters\\bigg.png",
"images\\Custom Font\\pngs\\big letters\\bigh.png",
"images\\Custom Font\\pngs\\big letters\\bigi.png",
"images\\Custom Font\\pngs\\big letters\\bigj.png",
"images\\Custom Font\\pngs\\big letters\\bigk.png",
"images\\Custom Font\\pngs\\big letters\\bigl.png",
"images\\Custom Font\\pngs\\big letters\\bigm.png",
"images\\Custom Font\\pngs\\big letters\\bign.png",
"images\\Custom Font\\pngs\\big letters\\bigo.png",
"images\\Custom Font\\pngs\\big letters\\bigp.png",
"images\\Custom Font\\pngs\\big letters\\bigq.png",
"images\\Custom Font\\pngs\\big letters\\bigr.png",
"images\\Custom Font\\pngs\\big letters\\bigs.png",
"images\\Custom Font\\pngs\\big letters\\bigt.png",
"images\\Custom Font\\pngs\\big letters\\bigu.png",
"images\\Custom Font\\pngs\\big letters\\bigv.png",
"images\\Custom Font\\pngs\\big letters\\bigw.png",
"images\\Custom Font\\pngs\\big letters\\bigx.png",
"images\\Custom Font\\pngs\\big letters\\bigy.png",
"images\\Custom Font\\pngs\\big letters\\bigz.png",
// "images\\Custom Font\\pngs\\big letters\\big�.png",
"images\\Custom Font\\pngs\\numbers\\0.png",
"images\\Custom Font\\pngs\\numbers\\1.png",
"images\\Custom Font\\pngs\\numbers\\2.png",
"images\\Custom Font\\pngs\\numbers\\3.png",
"images\\Custom Font\\pngs\\numbers\\4.png",
"images\\Custom Font\\pngs\\numbers\\5.png",
"images\\Custom Font\\pngs\\numbers\\6.png",
"images\\Custom Font\\pngs\\numbers\\7.png",
"images\\Custom Font\\pngs\\numbers\\8.png",
"images\\Custom Font\\pngs\\numbers\\9.png",
"images\\Custom Font\\pngs\\small letters\\smalla.png",
"images\\Custom Font\\pngs\\small letters\\smallb.png",
"images\\Custom Font\\pngs\\small letters\\smallc.png",
"images\\Custom Font\\pngs\\small letters\\smalld.png",
"images\\Custom Font\\pngs\\small letters\\smalle.png",
"images\\Custom Font\\pngs\\small letters\\smallf.png",
"images\\Custom Font\\pngs\\small letters\\smallg.png",
"images\\Custom Font\\pngs\\small letters\\smallh.png",
"images\\Custom Font\\pngs\\small letters\\smalli.png",
"images\\Custom Font\\pngs\\small letters\\smallj.png",
"images\\Custom Font\\pngs\\small letters\\smallk.png",
"images\\Custom Font\\pngs\\small letters\\smalll.png",
"images\\Custom Font\\pngs\\small letters\\smallm.png",
"images\\Custom Font\\pngs\\small letters\\smalln.png",
"images\\Custom Font\\pngs\\small letters\\smallo.png",
"images\\Custom Font\\pngs\\small letters\\smallp.png",
"images\\Custom Font\\pngs\\small letters\\smallq.png",
"images\\Custom Font\\pngs\\small letters\\smallr.png",
"images\\Custom Font\\pngs\\small letters\\smalls.png",
"images\\Custom Font\\pngs\\small letters\\smallt.png",
"images\\Custom Font\\pngs\\small letters\\smallu.png",
"images\\Custom Font\\pngs\\small letters\\smallv.png",
"images\\Custom Font\\pngs\\small letters\\smallw.png",
"images\\Custom Font\\pngs\\small letters\\smallx.png",
"images\\Custom Font\\pngs\\small letters\\smally.png",
"images\\Custom Font\\pngs\\small letters\\smallz.png",
// "images\\Custom Font\\pngs\\small letters\\small�.png",
"images\\Custom Font\\pngs\\symbols\\downArrow.png",
"images\\Custom Font\\pngs\\symbols\\leftArrow.png",
"images\\Custom Font\\pngs\\symbols\\rightArrow.png",
"images\\Custom Font\\pngs\\symbols\\symbol!.png",
// "images\\Custom Font\\pngs\\symbols\\symbol#.png",
"images\\Custom Font\\pngs\\symbols\\symbol$.png",
"images\\Custom Font\\pngs\\symbols\\symbol,.png",
"images\\Custom Font\\pngs\\symbols\\symbol..png",
"images\\Custom Font\\pngs\\symbols\\symbol=.png",
"images\\Custom Font\\pngs\\symbols\\symbol@.png",
"images\\Custom Font\\pngs\\symbols\\symbolHash.png",
"images\\Custom Font\\pngs\\symbols\\symbolQuestionMark.png",
"images\\Custom Font\\pngs\\symbols\\symbol~.png",
"images\\Custom Font\\pngs\\symbols\\upArrow.png",
"images\\sprites\\air grab\\AirGuy.png",
"images\\sprites\\air grab\\Bill.png",
"images\\sprites\\air grab\\Bill2.png",
"images\\sprites\\air grab\\Bill3.png",
"images\\sprites\\air grab\\Bill4.png",
"images\\sprites\\air grab\\leftArmm.png",
"images\\sprites\\air grab\\rightArmm.png",
"images\\sprites\\balloonPop\\balloonPopSpritesheet.png",
"images\\sprites\\Bird\\birdOpenFacingLeft.png",
"images\\sprites\\Bird\\birdOpenFacingRight.png",
"images\\sprites\\Bird\\plane.png",
"images\\sprites\\Bird\\skyRing.png",
"images\\sprites\\Bird\\skyRing2.png",
"images\\sprites\\bubbleWrap\\bubbleWrapSpritesheet.png",
"images\\sprites\\cVc shooter\\bullet.png",
"images\\sprites\\cVc shooter\\Gun.png",
"images\\sprites\\cVc shooter\\smokeParticle.png",
"images\\sprites\\cVc shooter\\target2.png",
"images\\sprites\\cVc shooter\\target3.png",
"images\\sprites\\dayTime\\arrow.png",
"images\\sprites\\dayTime\\speechBubbleFromLeft.png",
"images\\sprites\\dayTime\\speechBubbleFromLeftA.png",
"images\\sprites\\dayTime\\speechBubbleFromLeftAHighlighted.png",
"images\\sprites\\dayTime\\speechBubbleFromLeftB.png",
"images\\sprites\\dayTime\\speechBubbleFromLeftBHighlighted.png",
"images\\sprites\\dayTime\\speechBubbleFromRIght.png",
"images\\sprites\\dodgeBall\\dodgeBall.png",
"images\\sprites\\dodgeBall\\Player1.png",
"images\\sprites\\dodgeBall\\Player2.png",
"images\\sprites\\dodgeBall\\Player3.png",
"images\\sprites\\dodgeBall\\Player4.png",
"images\\sprites\\dodgeBall\\Player5.png",
"images\\sprites\\eggCatch\\Basket.png",
"images\\sprites\\eggCatch\\Basket2.png",
"images\\sprites\\eggCatch\\chicken.png",
"images\\sprites\\eggCatch\\egg.png",
"images\\sprites\\eggCatch\\egg2.png",
"images\\sprites\\feedGame\\cake1.png",
"images\\sprites\\feedGame\\cake2.png",
"images\\sprites\\feedGame\\cake3.png",
"images\\sprites\\feedGame\\cake4.png",
"images\\sprites\\feedGame\\leftP.png",
"images\\sprites\\feedGame\\rightP.png",
"images\\sprites\\Finder\\bottomRoom.png",
"images\\sprites\\Finder\\door.png",
"images\\sprites\\Finder\\upperAndMiddleRooms.png",
"images\\sprites\\Fishing\\boat.png",
"images\\sprites\\Fishing\\fish.png",
"images\\sprites\\Fishing\\fish2.png",
"images\\sprites\\Fishing\\fish3.png",
"images\\sprites\\Fishing\\person.png",
"images\\sprites\\Flower\\10 Second Flower.png",
"images\\sprites\\Flower\\Seed.png",
"images\\sprites\\Flower\\Seed2.png",
"images\\sprites\\Flower\\Simple Bee.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing Down.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing DownLeft.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing DownRight.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing Left.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing Right.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing Up.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing UpLeft.png",
"images\\sprites\\Flying Bee\\Simple Bee Facing UpRight.png",
"images\\sprites\\frogCrate\\bathStone.png",
"images\\sprites\\frogCrate\\bowl.png",
"images\\sprites\\frogCrate\\Bowl2.png",
"images\\sprites\\frogCrate\\cartoonFly.png",
"images\\sprites\\frogCrate\\cartoonFlyB.png",
"images\\sprites\\frogCrate\\editedBowlInside.png",
"images\\sprites\\frogCrate\\editedBowlOutside.png",
"images\\sprites\\frogCrate\\FrogInBowl.png",
"images\\sprites\\frogCrate\\frogTongue.png",
"images\\sprites\\frogRiver\\Frog.png",
// "images\\sprites\\frogRiver\\FrogInBowl.png",//does not exist
"images\\sprites\\frogRiver\\lilyImage1.png",
"images\\sprites\\frogRiver\\lilyImage2.png",
"images\\sprites\\frogRiver\\lilyImage3.png",
"images\\sprites\\frogRiver\\lilyImage4.png",
"images\\sprites\\Jumper\\JumperFacingLeft.png",
"images\\sprites\\Jumper\\JumperFacingRight.png",
"images\\sprites\\Jumper\\jumperGroundParticle.png",
"images\\sprites\\Jumper\\treasureChest.png",
"images\\sprites\\Lane\\billboard.png",
"images\\sprites\\Lane\\car.png",
"images\\sprites\\Lane\\gasCan.png",
"images\\sprites\\Maze\\mole.png",
"images\\sprites\\Maze\\moleFood.png",
"images\\sprites\\Memory\\Simon.png",
"images\\sprites\\Memory\\Simon2.png",
"images\\sprites\\Memory\\Simon3.png",
"images\\sprites\\Memory\\simonLeftHighlight.png",
"images\\sprites\\Memory\\simonRightHighlight.png",
"images\\sprites\\nightTime\\Ghost.png",
"images\\sprites\\nightTime\\ghost2.png",
"images\\sprites\\passBlock\\Gem.png",
"images\\sprites\\passBlock\\Gem2.png",
"images\\sprites\\passBlock\\Gem3.png",
"images\\sprites\\passBlock\\lavaBal.png",
"images\\sprites\\passBlock\\lavaBall.png",
"images\\sprites\\passBlock\\lavaBalll.png",
"images\\sprites\\passBlock\\lavaBalllUpsideDown.png",
"images\\sprites\\passBlock\\lavaBallUpsideDown.png",
"images\\sprites\\passBlock\\lavaBalUpsideDown.png",
"images\\sprites\\passBlock\\lavaParticle1.png",
"images\\sprites\\passBlock\\lavaParticle2.png",
"images\\sprites\\passBlock\\lavaParticle3.png",
"images\\sprites\\passBlock\\lavaParticle4.png",
"images\\sprites\\passBlock\\volcanicRock.png",
"images\\sprites\\Penalty\\goal.png",
"images\\sprites\\Penalty\\ball\\ball0000.png",
"images\\sprites\\Penalty\\ball\\ball0001.png",
"images\\sprites\\Penalty\\ball\\ball0002.png",
"images\\sprites\\Penalty\\ball\\ball0003.png",
"images\\sprites\\Penalty\\ball\\ball0004.png",
"images\\sprites\\Penalty\\ball\\ball0005.png",
"images\\sprites\\Penalty\\ball\\ball0006.png",
"images\\sprites\\Penalty\\ball\\ball0007.png",
"images\\sprites\\Penalty\\ball\\ball0008.png",
"images\\sprites\\Penalty\\ball\\ball0009.png",
"images\\sprites\\Penalty\\ball\\ball0010.png",
"images\\sprites\\pinata\\pinata.png",
"images\\sprites\\PromptsAndAnswers\\bee.png",
"images\\sprites\\PromptsAndAnswers\\cat.png",
"images\\sprites\\PromptsAndAnswers\\cot.png",
"images\\sprites\\PromptsAndAnswers\\flower.png",
"images\\sprites\\PromptsAndAnswers\\man.png",
"images\\sprites\\PromptsAndAnswers\\men.png",
"images\\sprites\\PromptsAndAnswers\\woman.png",
"images\\sprites\\PromptsAndAnswers\\women.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\helloMan.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\helloWoman.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\iLikeToEatVegetarian.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\whatDoYouLikeToEat.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\whatIsYourNameBaby.png",
"images\\sprites\\PromptsAndAnswers\\CentralVietnamese\\whatIsYourNameBrother.png",
// "images\\sprites\\PromptsAndAnswers\\Mandarin\\anyTime.png",//file exists but is invalid
"images\\sprites\\PromptsAndAnswers\\Mandarin\\anyTime2.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\at.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\black.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\blankCalendarPage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\blue.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\brown.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\couch.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\dumplings.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\excuseMeForSayingThis.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\excuseMePassingThroughContext.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\excuseMeQuestionAskingContext.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\excuseMyLowSkill.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\gray.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\green.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\have.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\here.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\horse.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howAmI.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howAreThey.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howAreWe.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howAreYou.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howIsHe.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howIsItDoing.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howIsShe.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\howOldAreYou.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iAlsoLikeFitness.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iAm37.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iAmATeacher.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iAmFromAmerica.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iAppreciateThat.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iLikeProgramming.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iLikeRockClimbing.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iLikeWatchingMovies.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iLiveInVietnam.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\illLetYouGo.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\imAlsoVeryGood.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\imVeryGood.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\in.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\iRespectfullyWait.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\itsMyDuty.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\itsOK.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\leImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\longTimeNoSee.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\mandarinBuy.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\mandarinMeMyIImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\mandarinSell.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\mandarinThatPlace.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\meToo.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\mom.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\myHumbleOpinion.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\myNameIsKiiiiiid.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\myNameIsSteven.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\niceToMeetYou.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\notBad.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\notImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\of.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\ofImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\oneMoment.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\personImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\pink.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\please.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\pleaseAdviseMe.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\pleaseHelpMe.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\purple.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\red.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\sleep.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\somethingElse.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\sorry.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\takeCare.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thankYou.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thatOne.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\there.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\theseOnes.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thisMaySeemRude.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thisOne.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thoseOnes.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\thumbnail.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\toBeImage.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\tower.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whatDoYouLikeToDo.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whatIsYourJob.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whatIsYourName.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whatPartOfChina.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whereAreYouFrom.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\whereDoYouLive.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\white.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\yellow.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\you.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\youHaveWorkedHard.png",
"images\\sprites\\PromptsAndAnswers\\Mandarin\\youreWelcome.png",
"images\\sprites\\Rewards\\Diamon2.png",
"images\\sprites\\Rewards\\Diamond.png",
"images\\sprites\\Rewards\\Gift.png",
"images\\sprites\\Rewards\\Gift2.png",
"images\\sprites\\Rewards\\Trophy.png",
"images\\sprites\\runner\\1.png",
"images\\sprites\\runner\\1edited.png",
"images\\sprites\\runner\\1jump.png",
"images\\sprites\\runner\\2.png",
"images\\sprites\\runner\\2edited.png",
"images\\sprites\\runner\\3.png",
"images\\sprites\\runner\\3edited.png",
"images\\sprites\\runner\\4.png",
"images\\sprites\\runner\\4edited.png",
"images\\sprites\\runner\\5.png",
"images\\sprites\\runner\\5edited.png",
"images\\sprites\\runner\\Basket.png",
"images\\sprites\\runner\\Coin.png",
"images\\sprites\\runner\\runnerCrouch.png",
"images\\sprites\\runner\\runnerJumping.png",
"images\\sprites\\runner\\runnerRunning1.png",
"images\\sprites\\runner\\runnerRunning2.png",
"images\\sprites\\runner\\runnerRunning3.png",
"images\\sprites\\runner\\runnerStumble.png",
"images\\sprites\\Snake\\apple.png",
"images\\sprites\\Snake\\appleCore.png",
"images\\sprites\\Snake\\bottomSnake.png",
"images\\sprites\\Snake\\middleSnake.png",
"images\\sprites\\Snake\\topSnake.png",
"images\\sprites\\spaceShooter\\Jupiter.png",
"images\\sprites\\spaceShooter\\Laser.png",
"images\\sprites\\spaceShooter\\rocket.png",
"images\\sprites\\spaceShooter\\rocketExplosion.png",
"images\\sprites\\spaceShooter\\spaceRock.png",
"images\\sprites\\spaceShooter\\spaceRock2.png",
"images\\sprites\\spaceShooter\\spaceship.png",
"images\\sprites\\spaceShooter\\spaceship2.png",
"images\\sprites\\SpellingBees\\Simple Bee Without Stripes.png",
"images\\sprites\\transitions\\heart.png",
"images\\sprites\\transitions\\star.png",
"images\\sprites\\Vacuum\\vacuum.png",
"images\\sprites\\whackAnAnswer\\wackPlacer.png",
"images\\sprites\\whackAnAnswer\\wackPlacer2.png",
"images\\sprites\\whackAnAnswer\\wackPlacer3.png",
"images\\sprites\\whackAnAnswer\\whackHammer.png",
"images\\sprites\\Penalty\\goalkeeper\\1.png",
"images\\sprites\\Penalty\\goalkeeper\\1rotated.png",
"images\\sprites\\Penalty\\goalkeeper\\2.png",
"images\\sprites\\Penalty\\goalkeeper\\3.png",
"images\\sprites\\Penalty\\goalkeeper\\4.png",
"images\\sprites\\Penalty\\goalkeeper\\5.png",
"images\\sprites\\Penalty\\goalkeeper\\6.png",
"images\\sprites\\Penalty\\goalkeeper\\7.png",
"images\\sprites\\Penalty\\goalkeeper\\8.png",
"images\\sprites\\Penalty\\goalkeeper\\9.png",
"images\\sprites\\Penalty\\goalkeeper\\10.png",
"images\\sprites\\Penalty\\goalkeeper\\11.png",
"images\\sprites\\Penalty\\goalkeeper\\12.png",
"images\\sprites\\Penalty\\goalkeeper\\13.png",
"images\\sprites\\Penalty\\goalkeeper\\14.png"];
